### PR TITLE
Us3 all main modules

### PR DESCRIPTION
**Pull request by enes3553**

### CODE REVIEW

**Review by IrenaStan4 — CHANGES_REQUESTED** [review]
thanks for updating Enes! can you just make a quick change before we merge? 
remove this lines:
public class DashboardPage {
    public DashboardPage() {
        PageFactory.initElements(Driver.getDriver(), this);
    }
    we already extend BasePage here and it has this lines

**Review by IrenaStan4 — COMMENTED** [review]
thanks

**Review by IrenaStan4 — COMMENTED** [review]
looks good

**Review by KristinaLuna — APPROVED** [review]

**Review by KristinaLuna — COMMENTED** [review]
make changes Irena requested :)

**Comment by enes3553** [comment]
thanks

**Review by IrenaStan4 — APPROVED** [review]
tnx :)

**Pull request merged**
