### PR TITLE
US1_ Please review and merge.

### PR DESCRIPTION
**Pull request by giuliana1**

### CODE REVIEW

**Review by KristinaLuna — COMMENTED** [review]
[REDACTED]

**Review by KristinaLuna — CHANGES_REQUESTED** [review]
Hi Giuliana!

a few things need to be changed:

1. remove @wip tag from cukes and leave the tag empty. We don't merge this, that's only for your personal use
2. in US1_login.feature: you and Chinara have same steps described in Given, When, And. You need to make these steps unique, otherwise, once merged the code will be duplicated and will fail. You can make your steps unique by adding US1 at the end of your step(Given user on the login page US1). The implementation of the code is good, just need to change description to make it unique. 
Thanks!

**Review by ChinaraOrujova — APPROVED** [review]
great job!

**Review by KristinaLuna — APPROVED** [review]

**Review by IrenaStan4 — APPROVED** [review]
Looks good :)

**Review by IrenaStan4 — APPROVED** [review]

**Review by IrenaStan4 — APPROVED** [review]

**Pull request closed without merging**
