### PR TITLE
US_14_isDone

### PR DESCRIPTION
**Pull request by Nadi86**
US1$ is done, please Review

### CODE REVIEW

**Review by IrenaStan4 — COMMENTED** [review]
Looks good Nadi :)
The only thing I see is you added:
@Given("user on the dashboard page")
    public void user_on_the_dashboard_page() {
        Driver.getDriver().get(ConfigurationReader.getProperty("trycloud.net.url"));
        loginPage.Login();
    }
    which we already defined in common step definitions, so if you want you can delete or we can remove it when we merge if it is causing conflict :)

**Review by KristinaLuna — CHANGES_REQUESTED** [review]
@Given("user on the dashboard page")
    public void user_on_the_dashboard_page() {
        Driver.getDriver().get(ConfigurationReader.getProperty("trycloud.net.url"));
        loginPage.Login();
    }
    
    this step is common for most people, it's defined in Dashboard_stepDefs, please delete it it, it will duplicate the code and make the whole project fail
    
    thanks :)

**Review by IrenaStan4 — APPROVED** [review]
looks good Nadi

**Review by KristinaLuna — APPROVED** [review]
nailed it!

**Comment by KristinaLuna** [comment]
pull request approved, merging changes!

**Pull request merged**
